apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: umbrella-admin-{{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
