apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-app-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: twitter-app
  template:
    metadata:
      labels:
        app: twitter-app
    spec:
      containers:
        - name: twitter-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
