apiVersion: v1
kind: Service
metadata:
  name: twitter-app-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: twitter-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
